name: CI Tests

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Run basic test
        env: 
          URL : ${{ secrets.AZ_POSTGRES }}
          MONGO : ${{ secrets.AZ_MONGO }}
        run: |
          echo "Building the .env file"
          echo "url=$URL" >> .env
          echo "mongo=$MONGO" >> .env

          echo "Running tests" 
          pip install -r requirements.txt
          pip install pytest
          
          pytest

